### ISSUE TITLE
problemo

### ISSUE THREAD

**Issue by RyanDreemurr** [WEGFan/Geometry-Dash-Savefile-Fix#2]
So I used the program when directed here by someone else, and it didn't really fix the problem, and nothing really changed. i'd appreciate the help! :D

**Comment by WEGFan** [comment]
Have you tried moving your savefiles to somewhere else and open the game?
If the game still doesn't open, then it's not the savefile corruption problem.
If it opens, would you mind sending your savefiles to my discord or email (but not attatch your savefiles to this issue here) to me so I can find out why my program didn't work.

**Comment by RyanDreemurr** [comment]
Sure! No problem. I do have to go to right now, so I'll check with that.
